
server:
  port: ${PORT:9005}
  

spring:
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    hibernate:
     ddl-auto: update 
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/inspiratti?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password:
  application:
    name: media-service

  cloud:
    azure:
      credential-file-path: my.azureauth  
      resource-group: blobstorage    
      region: Central India
      storage:
        account: blobstorageins
    
  jackson:
    serialization:
      fail-on-empty-beans: false

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  #contextPath: /resource
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8000/user
  


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  level:
    org:
      hibernate:
         SQL : DEBUG
         type:
           descriptor:
              sql:
                BasicBinder: TRACE

  feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
      
  
  